### ISSUE TITLE
Maintain HD Quality option causing auto-play issues

### ISSUE THREAD

**Issue by Twichigo** [FrankerFaceZ/Add-Ons#144]
Since [this commit](https://github.com/FrankerFaceZ/Add-Ons/commit/65bcdd9b9354462b6e9eeec497a8645bc977b225), whenever you open a stream in a new tab, video won't start playing and stays infinitely buffering (black screen) until you pause and un-pause it.
Turning Maintain HD Quality off removes the issue.

**Comment by Lordmau5** [comment]
Gonna @smokey019 for this one

**Comment by smokey019** [comment]
what browser do you use? and do you have other extensions enabled for twitch? ie: auto point/drop claimer for twitch etc

**Comment by Twichigo** [comment]
> what browser do you use? and do you have other extensions enabled for twitch? ie: auto point/drop claimer for twitch etc

Vivaldi, which is on Chrome engine. PC. I also use BTTV, which indeed has auto points and drop claimer built-in.

**Comment by smokey019** [comment]
> > what browser do you use? and do you have other extensions enabled for twitch? ie: auto point/drop claimer for twitch etc
> 
> Vivaldi, which is on Chrome engine. PC. I also use BTTV, which indeed has auto points and drop claimer built-in.

gotcha i can replicate this. i can look into finding a solution soon ™️

**Comment by smokey019** [comment]
fixed with this PR https://github.com/FrankerFaceZ/Add-Ons/pull/161

**Comment by Twichigo** [comment]
Any news on this one?
I have also noticed the same issue happens when you have an offline channel page open and then the stream starts - if the tab is not active, the player will stuck in the same black buffering state until you pause and un-pause it.
Also, when it's in this black screen state from any cause, changing the video quality doesn't fix it, even though normally it would refresh the stream i.e. standart buffering or delay would get fixed.

**Comment by smokey019** [comment]
still trying to find a fix

**Comment by Taizunz** [comment]
Update 1.2.1 unfortunately does not seem to have fixed this issue.

**Comment by smokey019** [comment]
as far as i know, there's no way to fix this for now

**Comment by Twichigo** [comment]
> as far as i know, there's no way to fix this for now

Since this only broke after specific commit, is it possible to revert the changes or re-implement parts of the older code?

**Comment by smokey019** [comment]
> > as far as i know, there's no way to fix this for now
> 
> Since this only broke after specific commit, is it possible to revert the changes or re-implement parts of the older code?

it didn't break after a specific commit. i tried a couple different things to get it to work and nothing seemed to actually make it work.

if you open a new browser after it crashes, it won't have this issue when you ask it to re-open tabs. but it only happens when you start a fresh browser.  so it's likely something to do with the browser and not necessarily the code.

commanderroot's script also has this same issue, so there's likely nothing we can do about it.  again, at least as far as i know.


the code is open source, so feel free to commit changes if you happen to find out what is causing it :)
